extensions:
  bearertokenauth:
    scheme: Bearer
    token: ${env:OTEL_API_KEY}
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: bearertokenauth
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: bearertokenauth

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  batch:
    timeout: 5s
    send_batch_size: 8192

exporters:
  prometheusremotewrite/mimir:
    endpoint: http://mimir:9009/api/v1/push
    remote_write_queue:
      enabled: true
      num_consumers: 2
      queue_size: 2000
    retry_on_failure:
      enabled: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 2000
    retry_on_failure:
      enabled: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 2000
    retry_on_failure:
      enabled: true

service:
  extensions:
    - bearertokenauth
    - health_check
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - prometheusremotewrite/mimir
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlphttp/loki
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlp/tempo
  telemetry:
    logs:
      level: info
